# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, conint


class DateRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: date_aliased = Field(..., alias='from')
    to: date_aliased


class SourceName(StrEnum):
    bracelet = 'bracelet'
    welltory = 'welltory'
    todoist = 'todoist'
    rescuetime = 'rescuetime'


class SourceRunStatus(StrEnum):
    success = 'success'
    partial = 'partial'
    failed = 'failed'
    not_run = 'not_run'


class QualityStatus(StrEnum):
    complete = 'complete'
    partial = 'partial'
    failed = 'failed'
    not_run = 'not_run'
    in_progress = 'in_progress'


class SourceStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: SourceName
    status: SourceRunStatus
    lastRunAt: AwareDatetime | None = None


class MetricPoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: AwareDatetime
    metric: str
    value: float
    unit: str | None = None


class TaskItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str
    timestamp: AwareDatetime


class Perspective(StrEnum):
    activity = 'activity'
    productivity = 'productivity'


class RescueTimeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: AwareDatetime
    perspective: Perspective
    label: str
    seconds: confloat(ge=0.0)


class BraceletSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sleepSeconds: float | None
    steps: float | None


class TodoistSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created: conint(ge=0)
    completed: conint(ge=0)


class SourceIndicator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: bool
    count: conint(ge=0)


class DayDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    braceletMetrics: list[MetricPoint]
    welltoryMetrics: list[MetricPoint]
    createdTasks: list[TaskItem]
    completedTasks: list[TaskItem]
    rescueTime: list[RescueTimeItem]


class DashboardDay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date_aliased
    weekday: conint(ge=1, le=7)
    currentDay: bool
    quality: QualityStatus
    sources: list[SourceStatus]
    bracelet: BraceletSummary
    welltory: SourceIndicator
    todoist: TodoistSummary
    rescuetime: SourceIndicator
    detail: DayDetail


class DashboardResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: date_aliased = Field(..., alias='from')
    to: date_aliased
    timezone: str
    generatedAt: AwareDatetime
    days: list[DashboardDay]


class SourceSyncSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: SourceName
    status: SourceRunStatus
    records: conint(ge=0)


class DashboardSyncResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: date_aliased = Field(..., alias='from')
    to: date_aliased
    sources: list[SourceSyncSummary]


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    details: dict[str, Any]
